# Generated by Django 3.1.5 on 2021-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemst',
            old_name='dec',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salemst',
            name='modified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
