# Generated by Django 3.1.5 on 2021-02-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210208_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='salemst',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
