# Generated by Django 3.1.5 on 2021-02-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210217_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledtl',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salemst',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salemst',
            name='disc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
