# Generated by Django 3.1.5 on 2021-05-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210228_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledtl',
            name='disc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='saledtl',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('qty', models.IntegerField()),
                ('mst', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.salemst')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
            ],
        ),
    ]
