# Generated by Django 3.1.5 on 2021-05-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210510_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRetMST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleRetDTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('qty', models.IntegerField()),
                ('mst', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.salemst')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRetMST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRetDTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('disc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('qty', models.IntegerField()),
                ('mst', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.salemst')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
            ],
        ),
    ]
